language: node_js
node_js:
  - "10.16.3"
  - "12"
sudo: false
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential git -y
  - sudo apt-get install libudev-dev -y
  - sudo apt-get install libusb-1.0-0-dev -y
  - sudo apt-get install gcc-4.8 g++-4.8 -y
after_success: npm run report && npm run coveralls
before_deploy:
  - "npm run build"
  # Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
  - |
    function npm_dist_tag() {
      if [[ "$TRAVIS_TAG" = *"-"* ]]; then
        echo "next"
      else
        echo "latest"
      fi
    }
deploy:
  - provider: npm
    email: dolcalmi@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    tag: $(npm_dist_tag)
    on:
      tags: true
      repo: dolcalmi/stellar-auth-client
      node: 10.16.3
  - provider: script
    script: "./bower_publish.sh"
    skip_cleanup: true
    on:
      tags: true
      repo: dolcalmi/stellar-auth-client
      node: 10.16.3
addons:
  firefox: 'latest'
env:
  global:
    secure: ZqqOkRIz+4EuKE53M8IoFvFHLvl8On3TdF63JuNiE+VbRBhUVtCW7Kh0DopYzt3KPn2gn5C2pleg8gCtViRWvgbrC8LlSpSWQ85aLlEC/Y9HKDEPsoVKol4MkAWHgW5aBStqswmjH65Fpx8z6dV7lwrCUiXBkhZ+drXUBnuJ02LQpy4jWTOhiu0pEXX03KnNdLE7n/SWirJUy0S6tP5G/b8RJQ0NJQeEKQ2NGn1Rt48MF5L0hiPaHdADmS5vEq2TqovWT+cQiIKkErKdnczHnU2xcnfxcauwK2iGa1t5u05v98IVXlY5Cry9K9WEkjh8+zcE/F/u+qGCGtbD07q0aGTsbK4TSWlyuxJQqepyOTUFOWtaZL3DPdA2EOB6ble8/eWZ0lBR6lAisrxCwXqm02Amv/PMkLEnc6JcuKqDLqYGz4CuYiB/9OAQPSZkC8BLSLkb+uiMUVEUvRCUF1k74XJ0+prvH4Qv62Eh/BZERUq7ILt015hdHOaPTsQl88dP0fWx9SPBIHn5q3uCJ5g8rCLXZThiH2LOPL21W88Kx3h6nub8/Rg2DN9SBkVrTWQVERP1SnhtQGCY7Jfeq4O+GCQVl4PQ8Him0eI/E9c76Nwh2sMQLVatdLlH/d3sSkon/I4ZhewzWkOyzdbxjyf7tBhjLwZcGGe23VQbJigmlus=
