language: node_js
node_js:
  - "8"
  - "10"
  - "12"
sudo: false
after_success: npm run report && npm run coveralls
deploy:
  - provider: npm
    email: dolcalmi@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    tag: $(npm_dist_tag)
    on:
      tags: true
      repo: dolcalmi/stellar-auth-client
      node: 8.16.0
