language: node_js
node_js:
  - "8"
  - "10"
  - "12"
sudo: false
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential git -y
  - sudo apt-get install libudev-dev -y
  - sudo apt-get install libusb-1.0-0-dev -y
  - sudo apt-get install gcc-4.8 g++-4.8 -y
after_success: npm run report && npm run coveralls
before_deploy:
  - "npm run build"
  # Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
  - |
    function npm_dist_tag() {
      if [[ "$TRAVIS_TAG" = *"-"* ]]; then
        echo "next"
      else
        echo "latest"
      fi
    }
deploy:
  - provider: npm
    email: dolcalmi@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    tag: $(npm_dist_tag)
    on:
      tags: true
      repo: dolcalmi/stellar-auth-client
      node: 8.16.0
addons:
  firefox: 'latest'
services:
  - xvfb
